name: snowflake_dev_py3.11
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - statsmodels
  - matplotlib
  - altair-all
  - plotly
  - pandas
  - numpy 
  - pyarrow
  - python=3.11
  - ipykernel
  - jupyter
  - snowflake-connector-python
  - snowflake-snowpark-python
  - streamlit